### ISSUE TITLE
Best approach for zoned heating, zone klep/motor and TRVs if needed.

### ISSUE THREAD

**Issue by brommetje** [nielsfaber/zoned-heating#10]
Situation house 1900, insulation moderate/reasonable, floorheating and rooted tone1 as a thermostat in the livingroom, then a connected OTGW, there is a zone valve in the supply of the underfloor heating, which can be controlled via a shelly, further radiators on the 1st floor and in the shower and laundry room , use Home Assistant (beginner) with zigbee and zwave, my problem is that the radiators do not heat up properly, due to the toon1 and floor heating in the livingroom. so want to make a kind of zone with zone valve to give radiators more and longer hot water if needed 3 TRVs available never used, what is the best approach?

**Comment by nielsfaber** [comment]
Closing old issues (please let me know if help is still needed).

**Comment by de-Techneut** [comment]
Have a similar setup. 

Groundfloor: Place of thermostat with floor heating.  Have an option to turn on/off the heating pump through a shelly switch. 
First and Second floor different rooms/zones with TRVs 

Ideal scenario:
* When ground floor temperature is already reached and a zone is requesting heat. Turn on the boiler to provide heat to the zone. And switch off the heating pump for the floor heating, this way non of the provided heat will go into the floor heating.
* When ground floor is below setpoint temperature and a zone is requesting heat. Leave the floor heating pump on and let the TRV of the zone do its thing. 

Could you make a solution were we can add a switch to turn on/off the ground floor heating depending if it needs heat or not?

**Comment by brommetje** [comment]
That would be a nice improvement and everything works even more optimally because you can now also temporarily switch off the underfloor heating. @Niels do you have the possibility to investigate and maybe to implement this or somebody else maybe.

**Comment by nielsfaber** [comment]
@de-Techneut 
> Could you make a solution were we can add a switch to turn on/off the ground floor heating depending if it needs heat or not?

How should this integration determine whether there is a need for heat downstairs?
Is there an entity in HA which exposes this information?
I don't think the data from the thermostat can be used, since this integration overrides the settings when it the TRVs demand heat.
Hence I don't really see a way to implement what you are asking.

**Comment by brommetje** [comment]
Maybe when ground floor temperature is reached (livingroom) then switch on a dummy switch and then when ground floor is below setpoint temperature switch off the dummy switch.

Or maybe when ground floor temperature is reached switch on a dummy switch on for a adjustable amount of time.

**Comment by brommetje** [comment]
Only question is now how do you known when the temperature in the living room is below setpoint temperature when other zones are still heating?

**Comment by de-Techneut** [comment]
> @de-Techneut
> 
> > Could you make a solution were we can add a switch to turn on/off the ground floor heating depending if it needs heat or not?
> 
> How should this integration determine whether there is a need for heat downstairs? Is there an entity in HA which exposes this information? I don't think the data from the thermostat can be used, since this integration overrides the settings when it the TRVs demand heat. Hence I don't really see a way to implement what you are asking.

I was checking my thermostat climate entity for it's attributes. These can be seen here:
![Schermafbeelding 2023-10-21 113548](https://github.com/nielsfaber/zoned-heating/assets/60130444/bb3fe13c-153e-4cc0-ad04-b8fd34a73680)
There is temperature (which is setpoint temperature)  and current temperature available.  

My thoughts are, when a zone is asking for heat. You increase the thermostat temperature to turn the boiler on, so the zone gets heat. But before  increasing the thermostat value, you save the current setpoint value of the thermostat to controle the switch  of the floor heating. Is room temperature above "original" setpoint, turn switch of. Is room temperature below "original" setpoint, turn switch on. 

In practice I'm not sure  if this works wel, but I would like to give this a try.
