### ISSUE TITLE
Error setting up entry Zoned Heating for zoned_heating

### ISSUE THREAD

**Issue by IMMIhomeassistant** [nielsfaber/zoned-heating#11]
sinse 2023.5 update the following error occured
there is no way to get it installed/activated

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/zoned_heating/__init__.py:27
Integration: Zoned Heating (documentation, issues)
First occurred: 20:32:54 (1 occurrences)
Last logged: 20:32:54

Error setting up entry Zoned Heating for zoned_heating
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/zoned_heating/__init__.py", line 27, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, [Platform.SWITCH])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by a8ree** [comment]
Came here to report the same issue

**Comment by stinobook** [comment]
I'm trying to fix it, I'll keep you guys posted if I succeed. Don't know if the owner is still maintaining this.

**Comment by a8ree** [comment]
Thanks @stinobook 
@nielsfaber has been active here recently

**Comment by nielsfaber** [comment]
I will look into this, no problem.
I'm glad to see people are still using this 🙂

**Comment by stinobook** [comment]
Great!

**Comment by stinobook** [comment]
https://github.com/stinobook/zoned-heating/commit/92218d1bd515a5991fe4010e4cc817e93eb08428

this makes it work again i presume. switch is present as an entity again.

please check with @nielsfaber  since i dont know python but just googled my way to this fix.

**Comment by IMMIhomeassistant** [comment]
Worked for me too, replace line 27 with:

`await hass.config_entries.async_forward_entry_setup(entry, "switch")`

**Comment by nielsfaber** [comment]
@stinobook provided a fix for this issue, thanks!
I created a first release based on this change.
I am planning to create new releases in case there are changes in the future, to make it easier to keep track of changes.
This issue can be closed now.

**Comment by a8ree** [comment]
Thanks @stinobook  and also @nielsfaber
