### ISSUE TITLE
Stored controller setpoint is overwritten?

### ISSUE THREAD

**Issue by hofst01** [nielsfaber/zoned-heating#18]
Hi,

I integrated your zoned-heating and it almost works perfectly!
I have a main thermostat from Intergas integrated in Home Assistant.
Everything works OK with adjusting the setpoint.
Also the correct previous setpoint is in the Stored controller setpoint.
But with Intergas it takes a while before the setpoint is read back.
I think your software is thinking this is a manual adjustment but it's not.
When the setpoint is read back the Stored controller setpoint is overwritten with this higher adjusted value.
So it will not return to the original setpoint.
The read back setpoint should not overwrite the Stored controller setpoint.

Do you have any suggestions?
Thx in advance!

**Comment by nielsfaber** [comment]
@hofst01 I'm glad to hear you like the integration.
> But with Intergas it takes a while before the setpoint is read back.

Do you have any idea of the delay between sending a setpoint and seeing it updated in the climate entity?

Currently the code is written assuming that this is instant. When the thermostat setpoint changes the integration assumes this is done by the user, so needs to be stored. Only while the integration updates the setpoint of your thermostat, this is not stored (but temporarily ignored).

Perhaps I could add some delay to help for your usage. 
I think this is a better approach than ignoring any setpoint change, because this would mean you cannot use the buttons on your thermostat anymore when zoned heating is active.

**Comment by hofst01** [comment]
Hello Niels Faber,

Today I did some research and testing.
I can't find anywhere for the Intergas integration what is the polling time.
So I did some testing.
In the worst case it took 2 minutes 23 seconds and in the best case 29 seconds.
Is a delay of for example 3 minutes possible?
Thx in advance!

**Comment by nielsfaber** [comment]
I added a new configurable setting for this:
<img src="https://github.com/nielsfaber/zoned-heating/assets/16861605/483b2f32-5282-4a13-be55-850899f06187" width="50%" height="50%">

It can be set anywhere between 10 and 300 seconds (=5 minutes).

When the integration changes the controller setpoint, the integration will not overwrite the stored controller setpoint during this time.
I hope it solves your problem.

**Comment by hofst01** [comment]
Hello Niels Faber,

Thank you for implementing the change! Looks very helpfull!
But I have been testing now, and nothing happens anymore (no activation, no override, no stored setpoint).
And sometimes I get the error "Kan service switch/turn_off niet aanroepen. HEAT" at operation of the switch.
This happens when normally the override should be active, but is not, and then operate the switch.

Any ideas?

Two entries in the log underneath:

Logboek Details (FOUT)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:17:15 (1 occurrences)
Last logged: 13:17:15

[139681345306944] HEAT
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/zoned_heating/switch.py", line 138, in async_turn_off
    await self.async_calculate_override()
  File "/config/custom_components/zoned_heating/switch.py", line 203, in async_calculate_override
    states = [
             ^
  File "/config/custom_components/zoned_heating/switch.py", line 204, in <listcomp>
    parse_state(self.hass.states.get(entity))
  File "/config/custom_components/zoned_heating/util.py", line 49, in parse_state
    data[ATTR_HVAC_ACTION] = HVACAction.HEAT
                             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: HEAT

Second Error:
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/zoned_heating/util.py:49
Integration: Zoned Heating (documentation, issues)
First occurred: 13:46:02 (1 occurrences)
Last logged: 13:46:02

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zoned_heating/switch.py", line 185, in async_zone_state_changed
    new_state = parse_state(new_state)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zoned_heating/util.py", line 49, in parse_state
    data[ATTR_HVAC_ACTION] = HVACAction.HEAT
                             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: HEAT

**Comment by nielsfaber** [comment]
I saw I made a small typo in the code. I corrected this and released it as v1.1.1. Hope this one works for you.

**Comment by hofst01** [comment]
Hello Niels,

Yeah! Thanks a lot. Now it works flawlessly!
Also with the delay, the stored controller setpoint is not overwritten.
End good, all good! Thank you!
