### ISSUE TITLE
Deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by msolomos** [nielsfaber/zoned-heating#21]
After the last update am getting the following warnings

HVAC_MODE_HEAT was used from zoned_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues
CURRENT_HVAC_HEAT was used from zoned_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues
HVAC_MODE_OFF was used from zoned_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues
CURRENT_HVAC_IDLE was used from zoned_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues
CURRENT_HVAC_OFF was used from zoned_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues

**Comment by LievenDeFoor** [comment]
Are you sure you're using the latest version?
From the code I see all these deprecated constants are already replaced by their new counterpart...

**Comment by nielsfaber** [comment]
Update your local installation to the latest version to fix this.
