### ISSUE TITLE
Detected that custom integration 'zoned_heating' calls `async_track_state_change` instead of `async_track_state_change_event`

### ISSUE THREAD

**Issue by msolomos** [nielsfaber/zoned-heating#30]
Detected that custom integration 'zoned_heating' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/zoned_heating/switch.py, line 146: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues

Detected that custom integration 'zoned_heating' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/zoned_heating/switch.py, line 151: async_track_state_change(, please create a bug report at https://github.com/nielsfaber/zoned-heating/issues

Any plans to update please ??? 

We love zone heating and is our number one integration!

**Comment by nielsfaber** [comment]
Thanks for informing me, I just made a new release that fixes the issue. Please update your local installation.
