### ISSUE TITLE
Thermostat not returning to previous state

### ISSUE THREAD

**Issue by stvnmbr1** [nielsfaber/zoned-heating#4]
The stored controller setpoint briefly shows previous state and then keeps the calculated temperature as stored setpoint.

Controller
climate.anna
Zones
climate.living_thermostat
Max setpoint
25
Override active
true
Temperature increase
1
Stored controller state
auto
Stored controller setpoint
23.2

**Comment by nielsfaber** [comment]
Closing old issues (please let me know if help is still needed).
