### ISSUE TITLE
Climate entity has only heat_cool available

### ISSUE THREAD

**Issue by klaassybrand** [nielsfaber/zoned-heating#6]
Hi, I would really like to use this setup for my multi-zone setup. I'm using a Busch Jaeger Free@home system which has an integration added in HA. I'm using 3 Free@home room thermostats which are connected to radiator thermal valves. 
![image](https://user-images.githubusercontent.com/117353642/206690975-7c3a09b6-58b5-49f9-a1d4-e61ac3e8aabd.png)

The point is the Room thermostats are vivible in HA with climate attribute of "heat_cool". As you stated this probably will not work (for now)

Now I'm really a newby to coding whatsoever but could you give a hint where to look for to make it work with the "heat_cool" climate attribute instead of the "heat".

Thanks!!

**Comment by nielsfaber** [comment]
Thanks for reaching out, I'm sure we can make it work.

Let's start by looking at the [definition](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes) of the `heat_cool` mode:
> HVACMode.HEAT_COOL | The device is set to heat/cool to a target temperature range.

In other words, depending on the difference between setpoint and current temperature, the device can be either heating or cooling.
Which seems a bit weird for a radiator?

It seems besides this, your device seems pretty normal (same as my Tado TRV).

Looking at the code, it seems quite doable to add support for it.
I think these items need to be updated:
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/util.py#L48
to
```
data[ATTR_HVAC_MODE] in [HVAC_MODE_OFF, HVAC_MODE_HEAT, "heat_cool"] 
```
https://github.com/nielsfaber/zoned-heating/blob/76fdbaf002545fa5d0a7fc29bfb8fe1a44b3bdd0/custom_components/zoned_heating/switch.py#L328

to 
```
if parse_state(self.hass.states.get(entity))[ATTR_HVAC_MODE] in [HVAC_MODE_HEAT, "heat_cool"]
```

be careful about the spaces/tabs placed in front, these should be kept as is.

For testing purposes you might want to enable debug logging by adding this to the configuration.yaml:
```yaml
  default: warning
  logs:
    custom_components.zoned_heating: debug
```
This way you will see quite some info of what the component does in the background.

Note that you will need to restart HA when making changes to the python code or the configuration.yaml.

Please give it a try and see how it goes.
I might be able to make some 'dummy' TRVs to test this locally as well if you get stuck.
The changes mentioned above are very minor and can be added to this project so it might help others too.

PS: I think it is harder to deal with a controller (i.e. the thermostat controlling the boiler) which has to be put in the heat_cool mode. But from your message I understand this is not the case for you, only the zone valves are the issue, right?

**Comment by klaassybrand** [comment]
Wow! This is great!! Thank you very much. I've just made these updates to the code. I'm not at home right now but testing remotely :-p.  Looks like it is working right now. THe main thermostat is updated right away and goes into heating mode. Now waiting for the reached setpoint temp.

**Comment by klaassybrand** [comment]
> In other words, depending on the difference between setpoint and current temperature, the device can be either heating or cooling.
> Which seems a bit weird for a radiator?

Yes these "RTR - room temperature controllers" from Busch Jaeger apparantly have the option to control cooling fan systems or airco units also. The RTR unit itself is acting as a normal room thermostat which is connected to a Heating actor module which controls the radiator valves.

**Comment by klaassybrand** [comment]
> PS: I think it is harder to deal with a controller (i.e. the thermostat controlling the boiler) which has to be put in the heat_cool mode. But from your message I understand this is not the case for you, only the zone valves are the issue, right?

This also had some configuration for me to work: I'm using an older Nefit Ecomline boiler and Moduline400 thermostat which is communicating over EMS-ESP via MQTT protocol. I used the EMS-ESP hardware module to connect via mqtt. THis is all the data i received from ESP regarding the thermostat control:
![image](https://user-images.githubusercontent.com/117353642/206725753-0e93b41c-42b5-4d0c-ad93-560a7d04a33a.png)

**Comment by nielsfaber** [comment]
It looks like it works as it should 👍 

Note that the integration simply calculates (for all zones that are on) the difference between the setpoint and current temperature, and adds this difference to the current temperature of your controller thermostat as setpoint.

21.5C seems a bit high, but hopefully this is only temporary (controller will be shut off when all the zones reached their temperature).

If you wish I could add a configurable parameter defining the ‘multiplier’ for calculating setpoint for the controller.
E.g. for 1C temperature increase requested by a zone, add only 0.5C to the setpoint of the controller.
This setting is really dependent on the size of the room where your main (controller) thermostat is placed vs the size of the rooms with the zones.

**Comment by klaassybrand** [comment]
Thanks again. RIght now i'm testing with only 2 zones, living and office. Living room right now is over setpoint temperature because of an actie wood stove.  I'm testing right now how the office is kept at a temperature of 13 degrees, (yes its low). It seems to be going nicely to the setpoint, heating turns off but after that the heating is not picking up again when temp drops below setpoint. Will try to look into debugging.

**Comment by klaassybrand** [comment]
> If you wish I could add a configurable parameter defining the ‘multiplier’ for calculating setpoint for the controller.
> E.g. for 1C temperature increase requested by a zone, add only 0.5C to the setpoint of the controller.
> This setting is really dependent on the size of the room where your main (controller) thermostat is placed vs the size of the rooms with the zones.

Would you say this little increase would be better in case of a modulating thermostat (Like i've got)?

**Comment by nielsfaber** [comment]
Closing old issues (please let me know if help is still needed).
