### ISSUE TITLE
Cannot select the device which control the zones

### ISSUE THREAD

**Issue by alexbratu88** [nielsfaber/zoned-heating#7]
When trying to configure the zoned-heating integration, after i select the device that controls the boiler, in the configure zoned heating settings, i do not see a dropdown from where to select the devices i want to mark as entities for different zones.
![image](https://user-images.githubusercontent.com/26311545/214089602-6a92e425-8aa9-4eab-a9eb-ff38614cd0cb.png)

**Comment by nielsfaber** [comment]
How many climate entities does your HA installation have?
There should be a list shown with all of them, except the one that was assigned as boiler controller.

**Comment by nielsfaber** [comment]
Closing old issues (please let me know if help is still needed).
