### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by msolomos** [nielsfaber/zoned-heating#9]
hello,

Are you aware of this Warning ??

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for zoned_heating using this method at custom_components/zoned_heating/__init__.py, line 27: hass.config_entries.async_setup_platforms(entry, [Platform.SWITCH])

How are you going to solve it ?

**Comment by nielsfaber** [comment]
This has become a breaking issue in the 2023.5 release, it has been fixed now.
Sorry for not taking action in an earlier stage.
